global:
  imagePullPolicy: Always
  ###vault:
  ###  host: ip
  ###  name: vault
  ###  vaultToken: someToken


frontend:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  service:
    port: 80
  ingress:
    host: front-ekaterinakaiser.2sem.students-projects.ru
    path: /
    pathType: Prefix
  containerPort: 80
  image:
    repository: your-username/sausage-store-frontend
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    postgresUri: jdbc:postgresql://postgresql-service:5432/sausage_store
    postgresUser: postgres
    postgresPassword: password
    reportPath: /logs/reports
    logPath: /logs
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  image:
    repository: your-username/sausage-store-backend
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  containerPort: 8080

backend-report:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 8080
  image:
    repository: your-username/sausage-store-backend-report
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  containerPort: 8080
  env:
    PORT: "8080"
    DB: "mongodb://mongodb-service:27017/sausage_store"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

infra:
  postgresql:
    image: postgres:13
    replicas: 1
    containerPort: 5432
    servicePort: 5432
    serviceType: ClusterIP
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    storage:
      size: 10Gi
      storageClass: standard
    env:
      POSTGRES_DB: sausage_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  mongodb:
    image: mongo:4.4
    replicas: 1
    containerPort: 27017
    servicePort: 27017
    serviceType: ClusterIP
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
