---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - front-ekaterinakaiser.2sem.students-projects.ru
      secretName: 2sem-students-projects-wildcard-secret
  rules:
    - host: front-ekaterinakaiser.2sem.students-projects.ru
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-{{ .Chart.Name }}-service
              port:
                number: {{ .Values.service.port }}