apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-report.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend-report.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      {{- include "backend-report.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend-report.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend-report.fullname" . }}-config
                  key: PORT
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend-report.fullname" . }}-secret
                  key: DB
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
