apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-report.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend-report.labels" . | nindent 4 }}
type: Opaque
data:
  DB: {{ printf "mongodb://reportuser:reportpassword@mongodb:27017/reports" | b64enc }}
